// Item Name: Blueberry - eCommerce Next JS template.
// Author: Maraviya Infotech
// Version: 1
// Copyright 2024

import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/store/Provider";
import Layout from "@/components/layout";

export const metadata: Metadata = {
  title: "Thandatti foods - eCommerce Next JS",
  description: "Generated by create next app",

  icons: {
    icon: "/assets/img/favicon/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
